plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}


loom {

    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "mixin/${mod_id}.mixins.refmap.json"
    }


    // Fabric Access Widener
    def aw = project(':common').file("src/main/resources/META-INF/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
        project.logger.debug('Fabric Access Wideners are enabled for this mod.')
    }


    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }

    }


    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

}


repositories {}


dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"

    mappings loom.layered {
        officialMojangMappings()

        // Parchment Mappings
        if (providers.gradleProperty("use_parchment_mappings").orNull?.toBoolean()) {
            parchment("org.parchmentmc.data:parchment-${parchment_minecraft_version}:${parchment_version}@zip")
        }
    }

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}


// DataGen
fabricApi {
    configureDataGeneration()
}


//
def loaderAttr = Attribute.of('mc.gradleconventions.loader', String)
loom.remapConfigurations.configureEach {
    configurations.named(it.name) {
        attributes {
            attribute(loaderAttr, 'fabric')
        }
    }
}
