// define your Plugins here required by sub-projects, repos for these can be added in root/settings.gradle

plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.126' apply(false)
    id 'fabric-loom' version '1.14-SNAPSHOT' apply(false)
}


// Links for Plugins listed above -

// legacyMDG - https://plugins.gradle.org/plugin/net.neoforged.moddev.legacyforge/, https://github.com/neoforged/ModDevGradle/blob/main/LEGACY.md/
// Fabric - https://fabricmc.net/develop/



// Repos for your sub-project's Dependencies not Plugins
repositories {}