# Gradle
org.gradle.jvmargs = -Xmx1G
org.gradle.daemon = false

# Mod
mod_id = mymod
mod_version = 1.0.0
minecraft_version = 1.19.2
mod_licence = licence

mod_name = My Mod
mod_authors = MyName
mod_credits = made by MyName
mod_description = mymod description.
mod_icon = mod_icon.png
mod_group = com.myname.mymod


# Forge
forge_loader_version = 43.5.0
forge_loader_version_range = [43,)
forge_minecraft_version_range = [1.19.2,1.20)

forge_at_enabled = false


# Fabric
fabric_api_version = 0.77.0+1.19.2
fabric_loader_version = 0.17.3

fabric_aw_enabled = false


# Extra
mod_web_homepage =
mod_web_update_json =
mod_web_source =
mod_web_issue_tracker =


# Jar
sources_jar_enabled = false
javadoc_jar_enabled = false
