plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}


legacyForge {

    version = "${minecraft_version}-${forge_version}"


    mixin {
        add (sourceSets.main, "mixin/${mod_id}.mixins.refmap.json")
        config ("mixin/${mod_id}.mixins.json")
    }


    // Forge Access Transformer
    def at = project(':common').file("src/main/resources/META-INF/${mod_id}.accesstransformer.cfg")
    if (at.exists()) {
        validateAccessTransformers = true
        accessTransformers = [at]
        project.logger.debug('Forge Access Transformers are enabled for this mod.')
    }


    // Parchment Mappings
    if (providers.gradleProperty("use_parchment_mappings").orNull?.toBoolean()) {
        parchment {
            minecraftVersion = parchment_minecraft_version
            mappingsVersion = parchment_version
        }
    }


    runs {

        client {
            client()
        }

        datagen {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        server {
            server()
        }

    }


    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

}


repositories {}


dependencies {
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
}


// DataGen
sourceSets.main.resources.srcDir 'src/generated/resources'


// Jar
tasks.named("jar", Jar).configure {
    finalizedBy('reobfJar')

    rename "${mod_id}.mixins.refmap.json", "mixin/${mod_id}.mixins.refmap.json"
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}