plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}


legacyForge {

    mcpVersion = minecraft_version


    // Common Access Transformer
    def at = project(':common').file("src/main/resources/META-INF/${mod_id}.accesstransformer.cfg")
    if (at.exists()) {
        validateAccessTransformers = true
        accessTransformers = [at]
        project.logger.debug('Common Access Transformers are enabled for this mod.')
    }


    // Parchment Mappings
    if (providers.gradleProperty("use_parchment_mappings").orNull?.toBoolean()) {
        parchment {
            minecraftVersion = parchment_minecraft_version
            mappingsVersion = parchment_version
        }
    }


    runs {

        client {
            client()

        }

        server {
            server()
        }

    }

}


repositories {}


dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
}


// Common Configurations
configurations {

    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }

    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }

}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}