plugins {
    id 'java'
    id 'org.spongepowered.gradle.vanilla'
    id 'maven-publish'
    id 'idea'
}


version = mod_version
group = mod_group

base {
    archivesName = "${mod_id}-${project.name}-${minecraft_version}"
}


minecraft {

    version(minecraft_version)

    runs {
        client("runClient") {
            workingDirectory(file("run"))
        }
        server("runServer") {
            workingDirectory(file("run"))
        }

    }

}


repositories {}


dependencies {
    compileOnly group:'org.spongepowered', name:'mixin', version:'0.8.5'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}


// Jar
tasks.named("jar", Jar).configure {
    // custom jar name
    //archiveFileName.set(""+".jar")
}


publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }

}
